%YAML:1.0
---
brightness_thresh: 200
blue_thresh: 50
red_thresh: 50
light_min_area: 1
armor_max_angle_diff: 15
armor_max_aspect_ratio: 6
armor_max_height_ratio: 2
armor_min_area: 200
small_armor_width: 1.2200000000000000e-01
big_armor_width: 2.2500000000000001e-01
armor_height: 4.4999999999999998e-02
