%YAML:1.0
---
brightness_thresh: 230
blue_thresh: 45
red_thresh: 60
light_min_area: 10
armor_max_angle_diff: 30
armor_max_aspect_ratio: 6
armor_max_height_ratio: 2
small_armor_width: 125
big_armor_width: 217
armor_height: 125
shift_scale: 7.5000000000000000e-01
number_thresh: 50
